lovelace:
  mode: yaml
  resources:
    - url: /local/three-state-switch-card/three-state-switch-card.js?v=0.1.5-minimal-thumb
      type: module

recorder:

history:

input_select:
  heating_mode:
    name: Heating mode
    options:
      - "On"
      - "Auto"
      - "Off"
    initial: "Auto"

input_boolean:
  heating_auto:
    name: Heating auto mode
    initial: true
  heating_manual:
    name: Heating manual output
    initial: false
  heating_external_force:
    name: Heating external force ON
    icon: mdi:flash
    initial: false

template:
  - binary_sensor:
      - name: Heating active
        unique_id: heating_active
        state: >-
          {{ is_state('input_boolean.heating_external_force', 'on') or
             is_state('input_boolean.heating_manual', 'on') }}
